# coding: utf-8

"""
    ratbag-emu

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ratbag_emu_client
from ratbag_emu_client.models.device import Device  # noqa: E501
from ratbag_emu_client.rest import ApiException


class TestDevice(unittest.TestCase):
    """Device unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDevice(self):
        """Test Device"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ratbag_emu_client.models.device.Device()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
