# coding: utf-8

"""
    ratbag-emu

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ratbag_emu_client
from ratbag_emu_client.api.device_api import DeviceApi  # noqa: E501
from ratbag_emu_client.rest import ApiException


class TestDeviceApi(unittest.TestCase):
    """DeviceApi unit test stubs"""

    def setUp(self):
        self.api = ratbag_emu_client.api.device_api.DeviceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ratbag_emu_server_add_device(self):
        """Test case for ratbag_emu_server_add_device

        Creates a simulated device  # noqa: E501
        """
        pass

    def test_ratbag_emu_server_device_event(self):
        """Test case for ratbag_emu_server_device_event

        Send an event to a simulated device  # noqa: E501
        """
        pass

    def test_ratbag_emu_server_get_device(self):
        """Test case for ratbag_emu_server_get_device

        Returns a simulated device  # noqa: E501
        """
        pass

    def test_ratbag_emu_server_list_devices(self):
        """Test case for ratbag_emu_server_list_devices

        List of simulated devices  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
