# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ratbag_emu_server.models.base_model_ import Model
from ratbag_emu_server import util


class EventData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """EventData - a model defined in OpenAPI

        :param data: The data of this EventData.  # noqa: E501
        :type data: List[int]
        """
        self.openapi_types = {
            'data': List[int]
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'EventData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EventData of this EventData.  # noqa: E501
        :rtype: EventData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this EventData.


        :return: The data of this EventData.
        :rtype: List[int]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this EventData.


        :param data: The data of this EventData.
        :type data: List[int]
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
