# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ratbag_emu_server.models.base_model_ import Model
from ratbag_emu_server import util


class MovementData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, x=None, y=None):  # noqa: E501
        """MovementData - a model defined in OpenAPI

        :param x: The x of this MovementData.  # noqa: E501
        :type x: int
        :param y: The y of this MovementData.  # noqa: E501
        :type y: int
        """
        self.openapi_types = {
            'x': int,
            'y': int
        }

        self.attribute_map = {
            'x': 'x',
            'y': 'y'
        }

        self._x = x
        self._y = y

    @classmethod
    def from_dict(cls, dikt) -> 'MovementData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MovementData of this MovementData.  # noqa: E501
        :rtype: MovementData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def x(self):
        """Gets the x of this MovementData.


        :return: The x of this MovementData.
        :rtype: int
        """
        return self._x

    @x.setter
    def x(self, x):
        """Sets the x of this MovementData.


        :param x: The x of this MovementData.
        :type x: int
        """
        if x is None:
            raise ValueError("Invalid value for `x`, must not be `None`")  # noqa: E501

        self._x = x

    @property
    def y(self):
        """Gets the y of this MovementData.


        :return: The y of this MovementData.
        :rtype: int
        """
        return self._y

    @y.setter
    def y(self, y):
        """Sets the y of this MovementData.


        :param y: The y of this MovementData.
        :type y: int
        """
        if y is None:
            raise ValueError("Invalid value for `y`, must not be `None`")  # noqa: E501

        self._y = y
